num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
print("Addition: ", num1+num2)
print("Substraction: ", num1-num2)
print("Multiplication: ", num1*num2)
print("Division: ", num1/num2)
print("Floor Divition: ", num1//num2)
print("Remainder: ", num1%num2)
print("Power: ", num1**num2)

n1 = int(input("Enter first number: "))
n2 = int(input("Enter second number: "))
print("Sum: ", n1+n2)
print("Difference: ", n1-n2)
print("Product: ", n1*n2)
print("Average: ", (n1+n2)/2)